DROP TABLE IF EXISTS SUBMISSION;
DROP TABLE IF EXISTS STUDENT_CLASS;
DROP TABLE IF EXISTS ASSIGNMENT;
DROP TABLE IF EXISTS CLASS;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
    id          INT PRIMARY KEY,
    username    VARCHAR(30) NOT NULL UNIQUE,
    password_hash INT NOT NULL,
    role        CHAR NOT NULL
);

CREATE TABLE CLASS (
    id          INT PRIMARY KEY AUTO_INCREMENT,
    name        VARCHAR(50) NOT NULL,
    teacher_id  INT NOT NULL,
    FOREIGN KEY (teacher_id) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ASSIGNMENT (
    id          INT PRIMARY KEY AUTO_INCREMENT,
    class_id    INT NOT NULL,
    name        VARCHAR(30) NOT NULL,
    status      CHAR NOT NULL,
    due         DATE,
    description TEXT,
    FOREIGN KEY (class_id) REFERENCES CLASS(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE STUDENT_CLASS (
    student_id  INT NOT NULL,
    class_id    INT NOT NULL,
    FOREIGN KEY (student_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (class_id) REFERENCES CLASS(id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (student_id, class_id)
);

CREATE TABLE SUBMISSION (
    student_id  INT NOT NULL,
    assignment_id INT NOT NULL,
    ext         varchar(5) NOT NULL,
    submitted_on DATE,
    FOREIGN KEY (student_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (assignment_id) REFERENCES ASSIGNMENT(id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY(student_id, assignment_id)
);

INSERT INTO USER VALUES(200137, 'ahsan', 123, 's');
INSERT INTO USER VALUES(200234, 'anas', 123, 's');
INSERT INTO USER VALUES(200327, 'hamdan', 123, 't');
INSERT INTO USER VALUES(200481, 'sarim', 123, 's');

INSERT INTO CLASS VALUES(NULL, 'Example Class A', 200327);
INSERT INTO CLASS VALUES(NULL, 'Example Class B', 200327);
INSERT INTO CLASS VALUES(NULL, 'Example Class C', 200327);

INSERT INTO ASSIGNMENT VALUES(NULL, (SELECT id FROM CLASS WHERE name='Example Class A'), 'Assignment 1', 'Do stuff', 'o');
INSERT INTO ASSIGNMENT VALUES(NULL, (SELECT id FROM CLASS WHERE name='Example Class B'), 'Assignment 1', 'Do stuff', 'o');
INSERT INTO ASSIGNMENT VALUES(NULL, (SELECT id FROM CLASS WHERE name='Example Class C'), 'Assignment 1', 'Do stuff', 'o');
INSERT INTO ASSIGNMENT VALUES(NULL, (SELECT id FROM CLASS WHERE name='Example Class A'), 'Assignment 2', 'Do stuff', 'o');
